### ISSUE TITLE
Add rules from a file

### ISSUE THREAD

**Issue by maelle** [ropensci/cchecks#15]
I'm wondering about a potential use case for `cchn_rules_add()`. Would it be of any use to be able to define a file `inst/cchecks-rules.yaml` in a package, that `cchn_rules_add()` could automatically recognize and use instead of a list (when the file exists)?

This way folks working on a package, co-maintainers, could agree on a set of notification rules and all subscribe to them easily.
It also means it'd be easier for sharing notification rules within an organization (copy-pasting `inst/cchecks-rules.yaml` from another repo).

This might all be totally useless.

**Comment by sckott** [comment]
I like the idea. the `yaml` pkg causes headaches in vcr pkg when there's non-ascii characters, but since we'd only have ascii characters in this use case its probably fine.
