### ISSUE TITLE
Rule for all my packages

### ISSUE THREAD

**Issue by llrs** [ropensci/cchecks#24]
Nice package! 
I wanted to make a rule to receive notifications for all my packages on CRAN, so submitted one with `cchn_rule_add`:

`package:-any, status:-OK, flavor:2, time:2, regex:`

Will this rule notify me of any package or just the ones I am the maintainer? (I suppose I will soon know, but at least this is a feature I would appreciate if this doesn't work as expected)

Will this package be submitted to CRAN?

**Comment by llrs** [comment]
Now realized it is already on the issue tracking on #23

**Comment by sckott** [comment]
Thanks for the issue @llrs ! Correct, we've already considered this in that other issue. Given your interest, I'll see about getting to that soon. 

It may get to CRAN. I have been waiting to see how interest in the notifications goes. So far not that many people are using it, 13 so far of the probably 10K or so maintainers

**Comment by llrs** [comment]
Don't worry, at the moment I only have 1 package on CRAN and it is not much trouble to track. 

Perhaps once on CRAN if it is announced on the mailing list (r-packages or r-packages-devel) might get more attention and users. On Bioconductor there is a [similar package](http://bioconductor.org/packages/release/bioc/html/BiocPkgTools.html) (without the notification service), so there is some interest on tools like that

**Comment by sckott** [comment]
Thanks, didn't know about the similar one in Bioc
